### PR TITLE
If text to be shown in bubble is empty, hide the bubble 

### PR DESCRIPTION
**Pull request by akgoswam**
It looks out of place that we simply show the bubble without text when text to show is empty. With this change, the bubble will be hidden using methods already provided.

### CODE REVIEW

**Comment by AndroidDeveloperLB** [comment]
You've tested it well, right?

**Comment by akgoswam** [comment]
Yes, we tested it out.
The main issue we had was the following: we have a fab button in the bottom right. To accomodate that, we also had the last recyclerview position to be empty. When scrolled to the bottom, the text is empty, which only shows the bubble.
That scenario was tested out.
And also tested out empty text in between as well. Worked fine.

**Comment by AndroidDeveloperLB** [comment]
Well I suggest that when the user drags the scroller, you should hide the FAB, because it doesn't make sense to be able to press it while scrolling.

**Comment by akgoswam** [comment]
Its not the FAB that's the blocker, its the empty holder at the end of the recyclerview. That always will have empty text.

**Comment by AndroidDeveloperLB** [comment]
Why did you put empty holder? Why not add margin to the last item?

That's what I did on my apps [here](https://play.google.com/store/apps/details?id=com.lb.app_manager&hl=en_US) and [here](https://play.google.com/store/apps/details?id=com.lb.contacts_sync&hl=en_US)

I wonder what's the more common solution for this.

**Pull request merged**
